id: P146174EA
initial_creation_type: ocr
source_metadata:
  volumes:
    b978c22f7a0e4002aed6b4d078fc25a5:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: རབ་ཏུ་གནས་པའི་རྒྱན།
      total_pages: 1853
      volume_number: 25
