id: P146174EA
initial_creation_type: ocr
source_metadata:
  volumes:
    429089ad6b764a588c9eb5d55cc46c92:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: རབ་ཏུ་གནས་པའི་རྒྱན།
      total_pages: 1853
      volume_number: 25
